compilation and cuda configuration fixes + vtk6 support
jhu-lcsr/ObjRecRANSAC pull request #1
Opened 2017-06-06 21:51 UTC by ahundt

2017-06-06 22:12 UTC, cpaxton requested changes

2017-06-06 22:12 UTC, cpaxton commented on CMakeLists.txt
> -cmake_minimum_required(VERSION 2.8.3)
why?

2017-06-06 22:12 UTC, cpaxton commented on src/BasicTools/CMakeLists.txt
> +cmake_policy(SET CMP0053 OLD)
Not supported in default Ubuntu version of cmake, please remove

2017-06-06 23:56 UTC, ahundt commented on CMakeLists.txt
> -cmake_minimum_required(VERSION 2.8.3)
warning about project name in ROS

2017-06-06 23:58 UTC, ahundt commented on src/BasicTools/CMakeLists.txt
> +cmake_policy(SET CMP0053 OLD)
shouldn't it just be a no-op in older versions?

2017-06-07 00:02 UTC, cpaxton commented on CMakeLists.txt
> -cmake_minimum_required(VERSION 2.8.3)
no, the cmake min version change

2017-06-07 00:03 UTC, cpaxton commented on src/BasicTools/CMakeLists.txt
> +cmake_policy(SET CMP0053 OLD)
Nope:
```
CMake Error at /home/chris.paxton/catkin_ws/src/ObjRecRANSAC/CMakeLists.txt:16 (cmake_policy):
  Policy "CMP0053" is not known to this version of CMake.


CMake Error at /home/chris.paxton/catkin_ws/src/ObjRecRANSAC/src/BasicToolsL1/CMakeLists.txt:3 (cmake_policy):
  Policy "CMP0053" is not known to this version of CMake.


CMake Error at /home/chris.paxton/catkin_ws/src/ObjRecRANSAC/src/BasicTools/CMakeLists.txt:3 (cmake_policy):
  Policy "CMP0053" is not known to this version of CMake.


CMake Error at /home/chris.paxton/catkin_ws/src/ObjRecRANSAC/src/ObjRecRANSAC/CMakeLists.txt:3 (cmake_policy):
  Policy "CMP0053" is not known to this version of CMake.


CUDA_TOOLKIT_ROOT_DIR not found or specified
CMake Error at /home/chris.paxton/catkin_ws/src/ObjRecRANSAC/s
```

2017-06-07 00:03 UTC, cpaxton commented on src/BasicTools/CMakeLists.txt
> +cmake_policy(SET CMP0053 OLD)
also please resolve conflicts

2017-06-07 04:20 UTC, ahundt commented on CMakeLists.txt
> -cmake_minimum_required(VERSION 2.8.3)
Probably doesn't need to be a separate project. This was a year or two ago so I don't remember for certain

2017-08-23 01:49 UTC, merged